version: 0.2
env:
  variables:
    PYPI_USERNAME: 'JohnPreston'
  parameter-store:
    PYPI_PASSWORD: /CodeBuild/pypipassword
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip --version && pip install pip --upgrade || curl https://bootstrap.pypa.io/get-pip.py | python
      - pip install twine
      - export BUILD_DIR=$PWD/builddir
  build:
    commands:
      - mkdir -p $BUILD_DIR
      - cd $BUILD_DIR
      - python3 setup.py sdist bdist_wheel
      - twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
